### ISSUE TITLE
Not working in Yosemite

### ISSUE THREAD

**Issue by morganestes** [Yeraze/CalendarHangout#3]
After upgrading to Yosemite, the script runs and says it's adding the URLs, but none of the events get updated in my calendar. 

I can't see any obvious errors (none in the log), and the output log shows a mix of "Processed `n` items in `n` seconds" and "Skipping, already captured" results, but none of the events reflect the changes.

UPDATE: I've tested the AppleScript by itself on a single event and watched the URL get added to the event, but immediately removed/reverted (not sure which).

**Comment by nhodges** [comment]
I am experiencing the same issue. Script runs fine but no URLs are added to Calendar.

**Comment by vlord3** [comment]
Having an issue with Yosemite:

If your browser is on a different machine then exit and re-run this
application with the command-line parameter 

  --noauth_local_webserver

Authentication successful.
Retrieving events from 2015-05-07T19:56:19.294842Z to 2015-05-21T19:56:19.294859Z
Found 76 events
launching calendar...
-> Device Certification Repository (DCR) Launch Team Kick-Off (Friday, May 08, 2015  10:30:00 AM) 
Traceback (most recent call last):
  File "./hangoutFix.py", line 174, in <module>
    main(sys.argv)
  File "./hangoutFix.py", line 149, in main
    processed = aScript.run()
  File "/Library/Python/2.7/site-packages/applescript/__init__.py", line 90, in run
    return self._unpackresult(*self._script.executeAndReturnError_(None))
  File "/Library/Python/2.7/site-packages/applescript/__init__.py", line 65, in _unpackresult
    raise ScriptError(errorinfo)
applescript.ScriptError: Calendar got an error: AppleEvent timed out. (-1712) app=u'Calendar' range=256-323

**Comment by J7mbo** [comment]
Here's my error in Yosemite when trying to install `pyobjc`:

    Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-gMEM6k/pyobjc-framework-AddressBook

**Comment by 2rs2ts** [comment]
This is happening to me, but there are no AppleScript errors nor pyobjc install errors. Logs are all successful, it just doesn't update the calendar. Same result with running the script manually as well as with launchctl.

**Comment by morganestes** [comment]
Preliminary tests on El Capitan show that it's working again. Not sure what changed, but I'll keep an eye out. 

I never did figure out why Yosemite balked at it.
